#!/bin/bash
# feedback.sh — collect hardware info + diagnosis outcome, auto-file a GitHub issue.
#
# Designed for AI assistants: after helping a user diagnose/fix their display
# artifacts, run this to close the loop and contribute a data point.
#
# Usage:
#   scripts/feedback.sh fixed|improved|no-change|mitigated [--freesync on|off|unknown] [--notes "…"]
#
# Privacy: collects display/hardware *model* info only — serial numbers are stripped.
set -euo pipefail

# system_profiler lives in /usr/sbin — ensure probes work in any caller environment
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

REPO="lcx0cd/mac-hdmi-freesync-fix"

RESULT="${1:-}"; [ $# -gt 0 ] && shift
case "$RESULT" in
  fixed|improved|no-change|mitigated) ;;
  *) echo "usage: $0 <fixed|improved|no-change|mitigated> [--freesync on|off|unknown] [--notes \"...\"]" >&2
     echo "  fixed     = no artifacts after wake (root cause resolved)" >&2
     echo "  improved  = less frequent / less severe" >&2
  echo "  no-change = turning FreeSync off did not help" >&2
     echo "  mitigated = artifacts still occur but wake daemon cleans them up" >&2
     exit 1 ;;
esac

FREESYNC="unknown"; NOTES=""
while [ $# -gt 0 ]; do
  case "$1" in
    --freesync) FREESYNC="$2"; shift 2 ;;
    --notes)    NOTES="$2";    shift 2 ;;
    *) shift ;;
  esac
done

# --- hardware probe (privacy: serial keys dropped in JSON parser) -----------
MAC_CHIP=$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "unknown")
MAC_MODEL=$(system_profiler SPHardwareDataType 2>/dev/null | grep "Model Name" | sed 's/.*: *//' || echo "unknown")
MACOS=$(sw_vers -productVersion 2>/dev/null || echo "unknown")

MODE=$( "${HOME}/.local/bin/display-resync" --status 2>/dev/null || echo "unknown" )

# Monitor identity + mode + connection. Privacy: serial keys dropped inside the
# JSON parser (never grep-filter the JSON stream — it can break parsing).
PROBE=$(system_profiler SPDisplaysDataType -json 2>/dev/null | /usr/bin/python3 -c '
import json,sys
try:
    d=json.load(sys.stdin)["SPDisplaysDataType"][0]
    nd=(d.get("spdisplays_ndrvs") or [{}])[0]
    nd={k:v for k,v in nd.items() if "serial" not in k.lower()}
    vid=nd.get("_spdisplays_display-vendor-id","")
    pid=nd.get("_spdisplays_display-product-id","")
    year=nd.get("_spdisplays_display-year","")
    name=nd.get("_name","")
    if name in ("","spdisplays_display"):
        name=f"Monitor {vid}-{pid}"
    if year: name+=f" ({year})"
    res=nd.get("spdisplays_resolution","unknown")
    print(f"{name} | {res} | {vid} {pid}")
except Exception:
    print("unknown | unknown | ")
' 2>/dev/null || echo "unknown | unknown | ")
MONITOR=$(echo "$PROBE" | cut -d'|' -f1 | xargs)
MODE=$( [ "$MODE" = "unknown" ] && echo "$(echo "$PROBE" | cut -d'|' -f2 | xargs)" || echo "$MODE" )
VIDPID=$(echo "$PROBE" | cut -d'|' -f3 | xargs)

CONNTYPE=$(ioreg -lw0 2>/dev/null | grep -qi "port-hdmi" && echo "HDMI" || echo "non-HDMI (DP/USB-C?)")

TODAY=$(date +%Y-%m-%d)

BODY=$(cat <<EOF
### Automated feedback (via scripts/feedback.sh)

| Field | Value |
|---|---|
| Outcome | **${RESULT}** |
| FreeSync / Adaptive-Sync (before) | ${FREESYNC} |
| Monitor | ${MONITOR} |
| Connection | ${CONNTYPE} |
| Mode | ${MODE} |
| Mac | ${MAC_MODEL} (${MAC_CHIP}), macOS ${MACOS} |
| Date | ${TODAY} |

**Notes**: ${NOTES:-_none_}

<sub>Generated by scripts/feedback.sh — raw hardware probe only, serials stripped. Maintainer: please add to data/verified-monitors.json.</sub>
EOF
)

# --- try automated submission via gh, else emit paste-ready text ------------
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  TMPB=$(mktemp)
  printf '%s\n' "$BODY" > "$TMPB"
  URL=$(gh issue create --repo "$REPO" \
        --title "[feedback] ${RESULT} — ${MONITOR} (${MAC_CHIP})" \
        --body-file "$TMPB" 2>/dev/null) && {
    echo "✅ Submitted: ${URL}"
    rm -f "$TMPB"; exit 0
  }
  rm -f "$TMPB"
  echo "⚠️  gh is available but issue creation failed — falling back to text output." >&2
fi

echo "Could not auto-submit (no gh auth). Paste this into https://github.com/${REPO}/issues/new?template=diagnosis-report.yml :"
echo "------------------------------------------------------------------------"
printf '%s\n' "$BODY"
